### ISSUE TITLE
how to delete old sync error

### ISSUE THREAD

**Issue by florentlagoda** [haiwen/seafile-client#1241]
Hi,
With new version 7.0.3 (on Ubuntu 18), my seafile-client icon always shows an exclamation point.
It's due to old sync error, but unable to delete this.
I have try to delete .ccnet/logs/ but not work.
![Capture d’écran_2019-11-09_10-49-39](https://user-images.githubusercontent.com/28236550/68528618-6bf9d680-02f5-11ea-9d61-2a3e8ddc0aa1.png)
![Capture d’écran_2019-11-09_10-50-02](https://user-images.githubusercontent.com/28236550/68528619-6c926d00-02f5-11ea-89f0-228a7d79d116.png)

How to disable this  old sync error ?

**Comment by rulistaff** [comment]
Same with windows client

**Comment by jobenvil** [comment]
Having the same isse on my end. I didn't found any solution yet. Any advice is wellcome.

**Comment by slewantoski** [comment]
Update to the newest client fixed this bug.

**Comment by jobenvil** [comment]
Thanks man!

**Comment by florentlagoda** [comment]
same on Linux i have the latest version. How to delete old sync error manually ? Where they are stored ?

**Comment by freeplant** [comment]
It can't be cleaned yet. The feature will be added later.

**Comment by jobenvil** [comment]
Perfect, thanks for clarifying.Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Daniel Pan <notifications@github.com> Datum: 21.11.19  02:59  (GMT+01:00) An: haiwen/seafile-client <seafile-client@noreply.github.com> Cc: jobenvil <elespiritudel82@gmail.com>, Comment <comment@noreply.github.com> Betreff: Re: [haiwen/seafile-client] how to delete old sync error (#1241) It can't be cleaned yet. The feature will be added later.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/haiwen/seafile-client/issues/1241?email_source=notifications\u0026email_token=AC3QJBOVY6EAV76ZFXDL36DQUXTQ5A5CNFSM4JLGLRK2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEYI32A#issuecomment-556830184",
"url": "https://github.com/haiwen/seafile-client/issues/1241?email_source=notifications\u0026email_token=AC3QJBOVY6EAV76ZFXDL36DQUXTQ5A5CNFSM4JLGLRK2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEYI32A#issuecomment-556830184",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by digital-spinner** [comment]
Nooo, this is a bug which is not resolved yet!

**Comment by florentlagoda** [comment]
For me it's resolved without doing anything (xubuntu)

**Comment by digital-spinner** [comment]
Then please tell me how to delete this log? It is useful but I need to clear it from time to time and get rid of the exclamation mark on tray icon.. So the issue is not resolved even in 7.0.4 client version.

**Comment by jobenvil** [comment]
@digital-spinner please read the 7th post of this thread

**Comment by digital-spinner** [comment]
Thanks, I have seen this. But why the issue is closed than if this is not resolved yet? But if you have some task to work on this than OK., I assume this will be fixed! BTW. Thanks for great 'own cloud' solution!

**Comment by jobenvil** [comment]
The issue is closed since the thread creator closed it. Your guess is correct, the seafile team is working on it. I assume it will be fixed soon as well, don't worry.
