### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by tkreind** [haiwen/seafile-client#1333]
Supporing apple silicon natively would be obviously beneficial and probably very simple. I'm attempting to do it myself but am struggling to build as I'm new to the project. Putting this here for visibility.

**Comment by killing** [comment]
The seafile client works on Apple Silicon.

**Comment by iammattmartin** [comment]
I think what @tkreind means is that a binary natively compiled for Apple Silicon instead of it having to use Rosetta.

Currently, seafile is the only app left not compiled as such and having to emulate x86.

So, to re-ask the question @killing, any chance of a native Apple Silicon binary to take advantage of power savings no doubt this will achieve.
