### ISSUE TITLE
TLS Initialization Failed on Linux 22.04 (PopOS)

### ISSUE THREAD

**Issue by s3rvant** [haiwen/seafile-client#1421]
After fresh install of PopOS 22.04 and then Seafile client install from:

https://help.seafile.com/syncing_client/install_linux_client/

I am seeing error:

![seafile](https://user-images.githubusercontent.com/39740665/179777102-be99f071-7b7a-4109-a572-ad77a591d0d3.png)

Appears to be an issue with OpenSSL ?

[applet.log](https://github.com/haiwen/seafile-client/files/9142025/applet.log)

**Comment by mpdl-knoth** [comment]
I can confirm the same issue on Ubuntu 22.04 LTS with Seafile-Client 8.05 and 8.07.

In the applet.log:

```[21.09.2022 16:59:05][network detector] resetting the qt network access manager
[21.09.2022 16:58:45][network detector] resetting the qt network access manager
[21.09.2022 16:58:45]QSslSocket::connectToHostEncrypted: TLS initialization failed
[21.09.2022 16:58:45][network detector] got a network failure: 99
[21.09.2022 16:59:05][api] network error for https://{DOMAIN}/api2/ping/: Die Initialisierung von TLS schlug fehl

**Comment by RaphaelWimmer** [comment]
In my case (Debian), the problem was that `/lib/x86_64-linux-gnu/libssl.so` pointed to `libssl.so.1.1`. Changing this symlink to `libssl.so.3` made Seafile work again. 

For future reference: the problem seems to lie not with seafile-applet itself but with qt.networking.ssl which complains about "Incompatible version of OpenSSL" (as seen with `ltrace seafile-applet`).
