### ISSUE TITLE
Seafile creates multiple copies of a file

### ISSUE THREAD

**Issue by MikeTango** [haiwen/seafile-client#1495]
Moin,

Seafile autouploader for pictures creates dozens of copies of the same picture, see screenshot. This eats bandwith like crazy. 

Running seafile 2.3.5 on android for upload, 8.0.5 on xubuntu on the computer.

Any ideas?

regards,

MT
![Uploading Bildschirmfoto_2023-11-07_09-18-48.png…]()

**Comment by zhwanng** [comment]
Hi, I have some questions
1, When installing Seafile 2.3.5 was it an uninstall and reinstall? Or did you clear the cache data of the Seafile APP?
2, Since I can't see the screenshot images, I can't know the information in the screenshot images. So the duplicate images were uploaded via which method? Photo backup or folder backup?
