### ISSUE TITLE
Don't create/propose default directory during installation

### ISSUE THREAD

**Issue by camlafit** [haiwen/seafile-client#153]
As we can specify directory target to each library. We can remove during installation the default directory. It's not needed.

People when synchronize select their directory and ignore often this first directory.

Should be improve UI behavior with a step in less

**Comment by Jip-Hop** [comment]
I was also confused by this. I chose a default directory on a removable external harddisk. I would like to sync libraries there by default. I checked the option "Do not automatically unseen a library when its local directory is removed or unaccessible for other reasons". So I thought everything should be working fine. Turns out the Seafile client stores a lof of important files in the default directory (inside .seafile-data). The Seafile client would not function properly when my external drive wasn't attached and I couldn't figure out why until I found the hidden folder .seafile-data.

**Comment by shoeper** [comment]
I like being able to set the path.
But one could give an option to select the default sync directory and an option for the cache folder.

**Comment by guillaume-uH57J9** [comment]
For people that relies and expect this feature, maybe this should be kept as an option (ie opt-in) ? 

There is a large set of application who decides they want to create their own working directory, directly inside the user's $HOME.
Seeing the same thing on my Windows' machine, various software (third party vendors, and even Microsoft's Visual Studio) decide they need to add their own stuff into the user's Home or Document folder. 

So the home/document folder are getting filled with cruft, and various folders/files. They usually stay empty since I already have my data ordely stored because installing these software.

It would be nice for seafile-client to stick the XDG specifications, and rely on the .local/share, and .cache folders. 
If additional folders need to be created/selected, please ask the user, don't decide for him.

Thanks

**Comment by camlafit** [comment]
Hi

An opt-in can be great. And in this case maybe propose by default home user
directory.

**Comment by Diermeier** [comment]
Hello, I have a question about that default directory caching behaviour.
My default directory for seafile is in my home dir on HDD-A (but the default dir is never used by me). On HDD-B I have the libraries in sync.
What happens if I restore a backup on HDD-A but not on HDD-B?
