### ISSUE TITLE
library description is mandatory

### ISSUE THREAD

**Issue by jans23** [haiwen/seafile-client#161]
When creating a new library, in addition to the title the user has to enter a description. Since there isn't a technical reason which requires this field and its annoying to the user, filling the description field should be changed to optional.

**Comment by tomchiverton** [comment]
+1

**Comment by freeplant** [comment]
We will remove library description in v5.0.

**Comment by tomchiverton** [comment]
On 28 March 2015 13:25:02 GMT+00:00, Daniel Pan <notifications@github.com> wrote:
>We will remove library description in v5.0.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/haiwen/seafile-client/issues/161#issuecomment-87227048

Remove? It is occasionally useful... 
-- 
Tom
Sent from my phone.

**Comment by ikcalB** [comment]
PLEASE bring back *library descriptions* as they are indeed useful!

Why not just make them optional??

**Comment by shoeper** [comment]
Although I would have also preferred to have an optional library description it has been removed to simplify the ui.

**Comment by JokerQyou** [comment]
Speaking of removed library description to simplify the UI, there's still a field named `Description` in the detail information dialog of libraries.
I found that very confusing. I've tried multiple times trying to find out how to create a library with description text, just because it's there and I thought that must be an optional feature. Now that you've removed it a long time ago, would you please kindly remove this field from library detail UI too?
![image](https://user-images.githubusercontent.com/1465267/48322564-2f07ef00-e663-11e8-9519-362ec5db54d5.png)

**Comment by freeplant** [comment]
It will be removed in the next release.
