### ISSUE TITLE
GnuCash file not synced by Seafile as it deleting and recreating file

### ISSUE THREAD

**Issue by jnuesch** [haiwen/seafile-client#247]
I use seafile to synchronise my gnucash database. It seems that the program deletes and recreates the database after each save. Under windows this works greate but under ubuntu the seafile client misses the recreation of the database after its deletion. When the client is restarted the new file will be seen and synchronised but not before.

**Comment by Jocbe** [comment]
This still seems to be a problem with Seafile 4.4.2 under 64-Bit Ubuntu. Restarting Seafile or renaming the affected file will results in Seafile detecting it again but upon a save in Gnucash it first disappears from Seafile.

**Comment by jnuesch** [comment]
Problem persist with Seafile 5.0.0 under 64-bit Ubuntu 15.10.

**Comment by freeplant** [comment]
We can reproduce the bug now.

**Comment by gBopHuk** [comment]
Still persist at
seafile-server 5.0.4 
seafile-client 5.0.4

**Comment by jnuesch** [comment]
I have still the problem with seafile-client 5.0.5 (server 5.0.4)

**Comment by mikapfl** [comment]
I can recreate the issue with sefile-server and seafile-client v6, both running on debian 8.
It is pretty annoying, I thought everything was working totally fine and now I can't access the file on my main computer and the laptop where I worked at is somewhere else. /-:

**Comment by adrianimboden** [comment]
I looked into it a little bit. The problem seems to be, that gnucash somehow manages to delete the file and the recreate it **with the correct content**, without triggering a CLOSE_WRITE event.

Only an IN_CREATE event gets received, but no CLOSE_WRITE.
I found the following comment:
 /* Nautilus's file copy operation doesn't trigger write events.
  * If the user copy a large file into the repo, only a create
  * event and a close_write event will be received. If we process
  * the create event, we'll certainly try to index a file when it's
  * still being copied. So we'll ignore create event for files.
  * Since write and close_write events will always be triggered,
  * we don't need to worry about missing this file.
  */

That comment obviously bases on a wrong assumption, as it is possible (I did not look into GnuCash, to see how it does it) to write a new file without triggering CLOSE_WRITE.

**Comment by killing** [comment]
Hi @adrianimboden 

Thank you for the detailed analysis. It helps to find the problem.

If I remember correctly, removing the Nautilus optimization will sometime make the indexing fail in the middle. This doesn't usually cause sync failure though, just a few error messages in the log.

We'll use this information to rethink about the event monitor algorithm.

Thanks

**Comment by jnuesch** [comment]
I still have the issue with 6.2.5. Will it be resolved in the next release?
