### ISSUE TITLE
client ignored directories create subdirectories while git operations

### ISSUE THREAD

**Issue by oliverlorenz** [haiwen/seafile-client#662]
Hi,

i created a seafile-ignore.txt with following content:

code/*

I hoped that will block all filesystem sync between the client and server. But it seems this doesn't work, because subdirectories (only empty directories) will be created on the server-side when a file has changed for example by a git clone.

#### Example:
first, create a library
do following operations on client side

    mkdir code
    echo "code/*" > seafile-ignore.txt
    cd code
    git clone git@github.com:haiwen/seafile-client.git

#### Result:
All sub directories will be created on the server

I am using ubuntu 14.10 seafile-clinet 4.2.5. If you need more informations, ask me ;)

Greedings,
Oliver

**Comment by Shanto** [comment]
This keeps taxing the CPU almost all the time while you work and your source tree/repo is large enough (100M files). I guess ignoring (from indexing) is getting important.

**Comment by niflostancu** [comment]
I have the same behavior too.

I'm trying to ignore all bower components:
```
Projects/*/bower_components/
Projects/*/bower_components/*
Projects/*/bower_components/*/
```
But it still creates an empty subfolder structure when I do a bower update. No files, just the folder hierarchy is getting synced.

And it gets messier when I use `bower link` (it creates a symlink to the real project source code):  seafile deletes my files when it syncs back the bower_components/ changes from another computer; only the folder structure remains, because it traverses the symlink from bower_components and deletes everything not existing on the server; then I have to restore my files from snapshot...

It would be okay if the ignored folders would get skipped from the indexing process / filesystem notification handler.

**Comment by killing** [comment]
This has been fixed.
