### ISSUE TITLE
OSX: Client does not recognise file changes in symlinked directories

### ISSUE THREAD

**Issue by tokred** [haiwen/seafile-client#679]
In order not to change my entire file system layout, I have several directories which I want cloud-synced linked into my library directory via symlink, e.g.:

```
./dir1/
./dir2 -> some/where/else/
./dir3 -> another/place/
./file1
./file2
```

Unfortunately, since a few versions the OSX Seafile Client does not pick up any file system changes in those symlinked directories (no log entry, nothing). They get synced only when I choose "Sync now" for the respective library.

Back in 4.0.x times, I am pretty sure this worked fine.

Any clue how to fix that? How can I help debugging?

**Comment by shoeper** [comment]
Ask Apple.

**Comment by tokred** [comment]
Thanks, but not very helpful.

After some digging, I am not sure if it is related to the issues https://github.com/haiwen/seafile-client/issues/524 or https://github.com/haiwen/seafile-client/issues/67.

I think both problems are FSEvents related, but I checked my folders with the 'find-fsevents-bugs' and they are not "broken". There are no non-ASCII chars in the directory structure either.

Problem could be reproduced with a "fresh" symlink in another library too. 

Any hint to track that down would be appreciated.

**Comment by igv** [comment]
I'm just trying out the latest version of Seafile for the first time, so don't how it worked before, but I can confirm that file changes on symlinks (both folders and files) are not triggering auto-sync.
Other cloud services (Dropbox, Copy.com) auto-sync the same symlinked folders just fine (immediately after the change), so I don't think that "Ask Apple" is going to hold in this case, it is obviously possible on OSX.

That said, as a workaround this is what I did for now: created a cronjob to touch every 5 minutes a hidden file .autosync inside top folder for synced library. That file will not be modified, so it won't pollute the transfer. Since I have symlinks only for the purposes of backup some files throughout my home folder, I have this problem in a single library (not too much overhead).

```
$ crontab -e
*/5 * * * * touch /Users/***/Seafile/Backup/.autosync
```

**Comment by shoeper** [comment]
Just because it works with e.g. dropbox it doesn't mean that they didn't implement a fix.
