### ISSUE TITLE
Hi resolution problems... again.

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [haiwen/seafile-client#702]
Following up from this issue:

https://github.com/haiwen/seafile/issues/895

In my Ubuntu, I spent about 3 hours setting every environment in my system to QT_DEVICE_PIXEL_RATIO=2. After spending all these hours, I discovered that QtCreator scales fine but Seafile doesn't.

Digging more into the issue, I found that Seafile is compiled on linux with Qt 4!!!!

You compile Seafile with Qt 5 with no problems in Windows. Why do you force Qt 4 on linux?

I tried to compile Seafile client myself, and I got this error message from cmake:

  Could NOT find Qt4 (missing: QT_MOC_EXECUTABLE QT_RCC_EXECUTABLE
  QT_INCLUDE_DIR QT_LIBRARY_DIR QT_QTCORE_INCLUDE_DIR QT_QTCORE_LIBRARY
  QT_QTGUI_INCLUDE_DIR QT_QTGUI_LIBRARY QT_QTNETWORK_INCLUDE_DIR
  QT_QTNETWORK_LIBRARY QT_QTDBUS_INCLUDE_DIR QT_QTDBUS_LIBRARY
  QT_UIC_EXECUTABLE) (found version "5.4.1")

Is there a way to fix this?

Thanks.

**Comment by lins05** [comment]
> Is there a way to fix this?

Have you installed the package "qtdeclarative5-dev"?

**Comment by samerafach** [comment]
@lins05 
Yesterday I succeeded in passing that point in compiling by enabling the option -DUSE_QT5=TRUE. My shock was using Qt 4 in the first place, where as you see in the other post a guy also spend lots of efforts trying to get his DPI right. 

About compiling, after spending some time on it, I reached a dead end, where I got a compilation error after getting the ccnet library and some others. Sorry I didn't write that down.

But can I please ask the developers to produce a Qt 5 version? There's no difference for you guys to do it compared to doing it with Qt 4, especially that it compiles on Qt 5 on Windows, so there's no reason why it won't compile on linux, since you know how to do it anyway.

Thank you.

**Comment by Burtan** [comment]
Any updates on compiling with Qt 5 for Linux?
