### ISSUE TITLE
Bad response code for GET <url>seafhttp/repo/locked-files: 404.

### ISSUE THREAD

**Issue by huegelc** [haiwen/seafile-client#716]
After searching through the log file of the 4.3.3 Linux Client I have noticed this line:

`[09/13/15 18:27:51] http-tx-mgr.c(1546): Bad response code for GET https://<url>/seafhttp/repo/folder-perm: 404.` 
`[09/13/15 18:27:51] http-tx-mgr.c(1824): Bad response code for GET https://<url>/seafhttp/repo/locked-files: 404.` 
Syncing seems to be fine though, but I´m wondering what causes this error.

**Comment by shoeper** [comment]
Are you using the community edition? Then you can ignore those. The feature is only available in the pro edition and that's why it throws a 404 not found when using the community edition.

Of course it would be better if the client wouldn't make these request when the server is not using the pro edition.

**Comment by huegelc** [comment]
Thank you for the hint. Indeed, it would be nice if the client checks the version of the server first before making those requests.
