### ISSUE TITLE
Feature: Rename filenames with special characters to sync everywhere

### ISSUE THREAD

**Issue by nilsbyte** [haiwen/seafile-client#731]
Hello, I have huge problems with syncing my seafile account when it comes to files containing special characters in filenames.

I often save .webloc or .url bookmark files to my seafile account under OSX. The files are named after the website title. Many websites use special characters such as pipes | in their website title. These files are synced to the server correctly (because the OSX file system allows these characters), but if my windows computer wants to sync them, it fails because the pipe character is not allowed in NTFS file systems (along with \ / : \* ? " < >).

An option in Seafile to rename files containing these characters to a standard character such as '-' would be very helpful. Dropbox does something similar afaik.

**Comment by shoeper** [comment]
I think the compromise so far was instead of not syncing those files at all they are synced as long as the operating system supports the.

**Comment by killing** [comment]
As stated in the Dropbox documentation, Dropbox doesn't change the file names. It just skip syncing those files to Windows. Anyway this issue is an edge case. In 5.0 version, we'll improve the handling a little bit. The files are still not synced to Windows. But when you remove the invalid characters from the file names on Mac, they'll be synced to Windows again.
