### ISSUE TITLE
Request raw download link

### ISSUE THREAD

**Issue by TheFreezebug** [haiwen/seafile-client#738]
This isn't really a bug, moreso a request. 

On the website for seafile, you can request a direct download link with ?raw=1 appended to it. 

![2015-10-24_17-05-19](https://cloud.githubusercontent.com/assets/3169571/10712777/99b45d04-7a71-11e5-92e7-545860975e0d.png)

Like above.

However on the client, your direct download link as seen as the "share seafile link" button appends ?dl=1.

Perhaps a way for a user to acquire a raw download link from the client could be added? 

I wouldnt request this if it weren't for the fact that ?dl=1 is 5 bytes and ?raw=1 is 6, so I couldn't just hex edit it in. 

![2015-10-24_16-59-34](https://cloud.githubusercontent.com/assets/3169571/10712785/f4b2a6f2-7a71-11e5-9639-a7476c6b0121.png)

**Comment by shoeper** [comment]
Afaik they differ. ?dl=1 forces the browser/client to download the file, ?raw=1 does not.

**Comment by ShonkyCH** [comment]
You can just manually edit the created link after it has been created (and similarly remove the part after and including the ? to open the file page without automatically downloading. Just change dl to raw and it will work fine. It's a bit manual though.

Yes, ?dl=1 will force it to download as a file rather than in the browser regardless of the file type. ?raw=1 would for example display a .jpg in the browser but an .exe would still download as the browser won't know what to do with it.

I agree though it's a bit inconsistent. I was confused as to the difference.
