### ISSUE TITLE
letsencrypt certificate not trusted

### ISSUE THREAD

**Issue by silberzwiebel** [haiwen/seafile-client#813]
Hi, 
I'm using seafile on an own server with a SSL certificate from let's encrypt. These certificates need to be refreshed rather often (every 2 months or so). 
While neither Firefox nor the seafile client on the desktop has any problem with a refreshed SSL certificate, seadroid 2.1.0 does not trust a new SSL certificate. Althoug it is a valid and not self-signed, seadroid says it is not valid and one needs to manually trust the certificate. In particular, there is no erro message if you do not open seadroid directly but rely on the automatic image sync function (which simply does not work then).

**Comment by shoeper** [comment]
Have you included the full chain?

**Comment by silberzwiebel** [comment]
Yes, I do think so.
I'm using nginx with the following options:

`ssl_certificate /etc/letsencrypt/live/domain.tld/fullchain.pem`
`ssl_certificate_key /etc/letsencrypt/live/domain.tld/privkey.pem`

**Comment by der-eismann** [comment]
I have no problems using an Let's Encrypt certificate (desktop, browser & Android app), but I use Apache, not nginx. So I would not make Seafile responsible for that.
(Apart from that I would recommend using the correct project for the Android client: https://github.com/haiwen/seadroid)

**Comment by shoeper** [comment]
I also have no problems using nginx but didn't test v2.1 so far. @der-eismann did you test it using seadroid 2.1?

**Comment by der-eismann** [comment]
Oh, didn't really notice that. I am still using 2.0.6 since this is the latest version from the Play Store. 
I downloaded 2.1.0 from F-Droid and can confirm that it is not trusting my LE certificate. I will open a bug report at the Seadroid project.

![screenshot_2016-06-25-00-35-14](https://cloud.githubusercontent.com/assets/10406217/16352282/37b98450-3a6d-11e6-9235-b5f61cf5aa07.png)

**Comment by FlorianLoch** [comment]
I also have these problems since I switched from a StartTLS to a Letsencrypt certificate. The certificate is correctly issued, the full chain up to DST X3 (you might check this at https://cloud.fdlo.ch). I am running server version 5.1.2 - but I am sure it is a client problem because it says so in the logs:

[06/27/16 22:02:44] http-tx-mgr.c(707): libcurl failed to GET https://cloud.fdlo.ch/seafhttp/protocol-version: Peer certificate cannot be authenticated with given CA certificates.

So to be precise it seems to be a problem caused by the version of libcurl used. According to 
```curl-config --version``` I am using version 7.43 - but requesting the landing page via curl itself works just fine, so I assume you deliver your own version of libcurl? 

This is a serious issue for me and probably for a whole lot of other people too, therefore I ask you to reopen it.

**Comment by shoeper** [comment]
Your server does not send the full chain according to https://www.ssllabs.com/ssltest/analyze.html?d=cloud.fdlo.ch&latest. (The intermediate crt is missing.)

**Comment by FlorianLoch** [comment]
I am sorry, @shoeper is right and my certificate doesn't contain the fullchain... I fixed that and Seafile client is happy again ;)

Still, I am wondering a little why it still worked with older versions and why Seafile indicates connection is alright by showing me a green link.
