### ISSUE TITLE
seaf-cli "No module named seafile" on Debian

### ISSUE THREAD

**Issue by moebius0x** [haiwen/seafile-client#865]
Running 'seaf-cli' will result in:
```
Traceback (most recent call last):
  File "/usr/bin/seaf-cli", line 86, in <module>
    import seafile
ImportError: No module named seafile
```
Installed packages:
```
seafile-cli:amd64 6.0.2-1
seafile-gui:amd64 6.0.0
ccnet:amd64 6.0.2-2
libccnet0:amd64 6.0.2-2
libjansson4:amd64 2.9-1
libseafile0:amd64 6.0.2-1
libsearpc1:amd64 3.0.8-1
python-searpc:amd64 3.0.8-1
seafile-daemon:amd64 6.0.2-1
```
uname -a:
`Linux hostname 4.9.0-1-amd64 #1 SMP Debian 4.9.2-2 (2017-01-12) x86_64 GNU/Linux`

binaries from:
`deb http://dl.bintray.com/seafile-org/deb jessie main`

seafile-applet is running fine.

**Comment by killing** [comment]
It should be caused by mixing official debian repos with the bintray repos. The debian official repo for Seafile is incomplete at the moment. It still lacks the gui package. We somehow missed the deadline of getting all packages into the official repo...

The problem should be solved after we update the bintray package to 6.0.3 version.
