### ISSUE TITLE
Sync status missing in Windows Explorer

### ISSUE THREAD

**Issue by Rojetto** [haiwen/seafile-client#916]
I'm using Seafile Client 6.0.6 and Seadrive 0.6.2 on Windows 10. I think there are supposed to be icons on files showing the current sync status? If so, for me these are missing both in libraries synced via the normal client, as well as in the mounted Seadrive.

**Comment by shoeper** [comment]
In the normal client it needs to be enabled in the settings.

**Comment by Rojetto** [comment]
Alright, I didn't know that. But I just checked and it supposedly was enabled the whole time.

**Comment by killing** [comment]
First of all, you have to re-login to your computer so that the icons can be shown.
And on Windows, only up to 15 icons can be registered. On Win10, OneDrive is installed and permanently occupies a few icons. So if you install a few file syncing softwares, some of them cannot show the icons.
In general, I don't think this is a bug. So I'll close this issue.

**Comment by Rojetto** [comment]
Okay, thanks for the explanation. I researched this myself a little and HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShellIconOverlayIdentifiers already contains 16 icons for OneDrive and Dropbox alone, meaning even Dropbox can't display one. Really seems like you can't do anything, but what the heck Microsoft?

**Comment by Creling** [comment]
@killing hey, it seems that Seafile Client cannot show sync status in Windows 11, am I right?
